apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: kubebrick-ui
    app.kubernetes.io/component: kubebrick-ui
    app.kubernetes.io/instance: kubebrick-ui  
  name: kubebrick-ui
spec:
  lookupPolicy:
    local: false