{{- $brokername  := .Values.microservices.config.kubebrick.brokername -}}
{{- range .Values.microservices.config.kubebrick.queues }}
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: {{ $brokername }}-{{ . |title|lower}}-address  
spec:
  addressName:  {{ . |lower}}
  queueName:  {{ . |lower}}
  routingType: anycast
---
{{- end }}