apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: gitops/microshift/injection-machine-chart
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: injection
  name: injection-subscription-1
  namespace: injection
spec:
  channel: injection/injection
  placement:
    placementRef:
      kind: PlacementRule
      name: injection-placement-1

