{{- range .Values.pipelines.pvcs }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ . |lower}}-pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem  
---
{{- end }}  