apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: debezium-kafka
  name: kubebrick-connector-postgres
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.dbname: kubebrick
    database.hostname: packaging-machinedb
    database.password: password1
    database.port: 5432
    database.server.name: kubebrick
    database.user: postgres
    plugin.name: pgoutput
  tasksMax: 1