apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: print-service-proxy-pipeline
  spec:
    description: A java springboot ReST service pipeline
    params:
    - default: {{ .Release.Namespace }}
      description: The target namespace
      name: target-namespace
      type: string
    - default: print-service-proxy
      description: The application name
      name: application-name
      type: string         
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: {{ .Values.pipelines.giturl }}
      - name: deleteExisting
        value: "true"
      - name: subdirectory
        value: "printserviceproxy"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: workspace-acme
    - name: build-app
      params:
        - name: sub-project-name
          value: print-service-proxy
        - name: workspace-subdir
          value: printserviceproxy
      runAfter:
      - fetch-repository
      taskRef:
        name: maven-quarkus-build
      workspaces:
      - name: source
        workspace: workspace-acme        
    - name: create-app-image
      params:
      - name: namespace
        value: $(params.target-namespace)
      - name: buildconfig-name
        value: print-service-proxy
      - name: dir-file-path
        value: /workspace/source/printserviceproxy/dev/microservices/print-service-proxy/target/quarkus-app
      runAfter:
      - build-app
      taskRef:
        name: java-binary-deploy
      workspaces:
      - name: source
        workspace: workspace-acme
    - name: rollout-app
      params:
      - name: namespace
        value: $(params.target-namespace)
      - name: deployment-name
        value: $(params.application-name)          
      runAfter:
      - create-app-image
      taskRef:
        name: deployment-rollout
      workspaces:
      - name: source
        workspace: workspace-acme        
    workspaces:
    - name: workspace-acme
kind: List
metadata: {}