apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: sorting-machine
    app.kubernetes.io/component: sorting-machine
    app.kubernetes.io/instance: sorting-machine  
  name: sorting-machine
spec:
  lookupPolicy:
    local: false