apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: sorting
  namespace: sorting
spec:
  type: Git
  pathname: 'https://github.com/redhat-italy/kubebrick-showcase'

