apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: gitops/microshift/sorting-machine-chart
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: sorting
  name: sorting-subscription-1
  namespace: sorting
spec:
  channel: sorting/sorting
  placement:
    placementRef:
      kind: PlacementRule
      name: sorting-placement-1

