apiVersion: v1
kind: Service
metadata:
  labels:
    template: postgresql-ephemeral-template    
  name: {{ .Values.packagingmachinedb.servicename }}
spec:
  ports:
  - name: postgresql
    port: {{ .Values.packagingmachinedb.port }}
    protocol: TCP
    targetPort: {{ .Values.packagingmachinedb.port }}
  selector:
    name: {{ .Values.packagingmachinedb.servicename }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
