apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: kubebrick-webapp
    app.kubernetes.io/component: kubebrick-webapp
    app.kubernetes.io/instance: kubebrick-webapp  
  name: kubebrick-webapp
spec:
  lookupPolicy:
    local: false