apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kubebrick-webapp
    app.kubernetes.io/component: kubebrick-webapp
    app.kubernetes.io/instance: kubebrick-webapp
  name: kubebrick-webapp
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: kubebrick-webapp
    weight: 100
  wildcardPolicy: None