apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-quarkus-build
spec:
  workspaces:
  - name: source
    description: The workspace where the source code will found
  steps:  
  - name: build
    image: maven:3.8-jdk-11
    command: ["/bin/bash", "-c"]      
    args:
    - /usr/bin/mvn -f /workspace/source/injectionmachine/dev/microservices/injection-machine-service/pom.xml -s /workspace/source/injectionmachine/dev/microservices/injection-machine-service/custom-settings.xml clean package -DskipTests=true -Dmaven.repo.local=/workspace/source/m2



