apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: packaging-machine
    app.kubernetes.io/component: packaging-machine
    app.kubernetes.io/instance: packaging-machine  
  name: packaging-machine
spec:
  lookupPolicy:
    local: false