apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kubebrick-webapp
    app.kubernetes.io/component: kubebrick-webapp
    app.kubernetes.io/instance: kubebrick-webapp
  name: kubebrick-webapp
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: kubebrick-webapp:{{ .Values.application.config.kubebrick.webapp.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.application.config.kubebrick.webapp.baseimage }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5