apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorting-machine
  labels:
    app: sorting-machine
    version: v1  
    {{- include "kubebrick-factory.labels" . | nindent 4 }}    
    app.kubernetes.io/name: camel
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "kubebrick-factory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: sorting-machine
        version: v1
        {{- include "kubebrick-factory.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sorting-machine
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: QUARKUS_HTTP_PORT 
              value: '8080'  
            - name: QUARKUS_QPID_JMS_URL
            {{ if .Values.microservices.config.kubebrick.externalbroker }}
              value: '{{ .Values.microservices.config.kubebrick.externalbrokerurl }}'
            {{ else }}
              value: 'amqp://{{ .Values.microservices.config.kubebrick.brokername }}-hdls-svc.{{ .Release.Namespace }}.svc.cluster.local:5672'
            {{ end }}  
            - name: JAVA_APP_JAR
              value: 'quarkus-run.jar'    
            {{ if .Values.microservices.config.kubebrick.externalbroker }}        
            - name: JAVA_OPTS
              value: '-Djavax.net.ssl.trustStore=/var/keystore/client.ts -Djavax.net.ssl.trustStorePassword=123456'          
            {{ end }}      
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5              
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
        {{- if .Values.microservices.config.kubebrick.externalbroker }}        
          volumeMounts:
            - mountPath: "/var/keystore"
              name: client-keystore
              readOnly: true    
        {{- end }}                
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
     {{- if .Values.microservices.config.kubebrick.externalbroker }}        
      volumes:
        - name: client-keystore
          secret:
            secretName: amq-client-trustore
      {{- end }}              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
