# Default values for kubebrick-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/kubebrick/packaging-machine:1.0
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

microservices:
  config:
    kubebrick:
      externalbroker: true
      brokername: "amq-broker"
      externalbrokerurl: "amqps://amq-broker-all-0-svc-rte-kubebrick-amq.apps.ccnr-appdev.sandbox1331.opentlc.com:443?sslEnabled=true"
      packagingmachine:
        baseimage: "openjdk-11-rhel8:1.0"
        tag: "1.0" 
        queues:        
          - bluepieces
          - greenpieces          
          - redpieces
      ocphostdomain: .cluster.openshift.mydomain.xyz                         

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
