apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: injection-machine
    app.kubernetes.io/component: injection-machine
    app.kubernetes.io/instance: injection-machine  
  name: injection-machine
spec:
  lookupPolicy:
    local: false