apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: print-service-proxy
    app.kubernetes.io/component: print-service-proxy
    app.kubernetes.io/instance: print-service-proxy  
  name: print-service-proxy
spec:
  lookupPolicy:
    local: false