apiVersion: v1
kind: Service
metadata:
  labels:
    app: sorting-machine
    app.kubernetes.io/component: sorting-machine
    app.kubernetes.io/instance: sorting-machine
  name: sorting-machine
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sorting-machine
  sessionAffinity: None
  type: ClusterIP