apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: gitops/microshift/packaging-machine-chart
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: packaging
  name: packaging-subscription-1
  namespace: default
spec:
  channel: packaging/packaging
  placement:
    placementRef:
      kind: PlacementRule
      name: packaging-placement-1

