kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubebrick-webapp-pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem