apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: packaging-notification
    app.kubernetes.io/component: packaging-notification
    app.kubernetes.io/instance: packaging-notification  
  name: packaging-notification
spec:
  lookupPolicy:
    local: false