apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: packaging-notification
    app.kubernetes.io/component: packaging-notification
    app.kubernetes.io/instance: packaging-notification
  name: packaging-notification
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: packaging-notification:{{ .Values.microservices.config.kubebrick.packagingnotification.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.microservices.config.kubebrick.packagingnotification.baseimage }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5