apiVersion: v1
kind: Service
metadata:
  labels:
    app: packaging-notification
    app.kubernetes.io/component: packaging-notification
    app.kubernetes.io/instance: packaging-notification
  name: packaging-notification
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: packaging-notification
  sessionAffinity: None
  type: ClusterIP