apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: {{.Values.microservices.config.kubebrick.brokername}}
spec:
  acceptors:
    - expose: false
      name: amqp
      port: 5672
      protocols: AMQP
#  addressSettings:
#    applyRule: SortingBelt
  adminPassword: amq
  adminUser: amq
  console:
    expose: true
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1
