apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: sorting-machine
    app.kubernetes.io/component: sorting-machine
    app.kubernetes.io/instance: sorting-machine
  name: sorting-machine
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sorting-machine:{{ .Values.microservices.config.kubebrick.sortingmachine.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.microservices.config.kubebrick.sortingmachine.baseimage }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5